eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka-url:http://localhost:8761}/eureka


spring:
  application:
    name: account-ms
  datasource:
    url: jdbc:postgresql://localhost:5433/unitech
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: none
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: api-docs

server:
  port: 8888
  servlet:
    context-path: /account-ms
