eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka-url:http://localhost:8761}/eureka


spring:
  application:
    name: currency-rate-ms
  datasource:
    url: jdbc:postgresql://localhost:5433/unitech
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: none
    show-sql: true

jwt:
  key: secret
  issuer: unitech

server:
  port: 8889
  servlet:
    context-path: /currency-rate
