eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka-url:http://localhost:8761}/eureka

spring:
  application:
    name: auth-user-ms
  datasource:
    url: jdbc:postgresql://localhost:5433/unitech
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: none
    show-sql: true


server:
  port: 8887
  servlet:
    context-path: /auth-user

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: api-docs

jwt:
  key: fhsuhASfn34GD
  issuer: uni-tech